For a discrete stochastic process with a finite state set, what is the probability for the occurence of a randomly chosen sequence with states permutation of length $N$? Let's say, for the easy model with two states and a given transition probability matrix, that is:

$$
\mathbb{S} = \left\{ 1, 2 \right\}, ~ P = \begin{pmatrix}
                             0.3 & 0.7\\
                             0.4 & 0.6
                            \end{pmatrix}
$$

Here, $\mathbb{S}$ is the state space. In transition matrix $P$, $P_{ij}$ stands for the probability of a single step transition from $i$ to $j$.

**Proposition**

A transition matrix $P$ is **regular**, if there exists $k \in \mathbb{N}^{+}$, such that every element in $P^{(k)}$ is strictly positive.

**Theorem**

A discrete Markov Chain has a limiting distribution if it has a regular transition matrix.

(Here I am not going to prove the Theorem above.)

For the question stated in the first sentence, it is very obvious that the answer highly depends on whether we chose the sequence at the beginning, or whether we should regard the first element of the sequence as the given initial condition? Just imagine an extreme condition, like $\left\{ 1 \right\}$ is an absorbing state set, and we just appointed state $\left\{ 1 \right\}$ as initial condition. If yes, then for concluding the final reason, we must clarify the probability distribution of the initial selection.

However, what if this information is not provided? After a moment thought, I think the answer relates the following points:

1. As the source of my intuition, since the geometric series with parameter less than 1 finally converge, will the difference brought by initial conditions be diluted by the time too? In other words, will the probability finally converge to a fixed amount?

2. If the convergence cannot be reached, or the initial difference cannot be diluted, then we have to assign a artificial prior distribution, as stated before. 

Clearly, point $1$ really needs the assumption that $P$ is regular, otherwise it produces conflict with our extreme example mentioned above.

From my mathematical intuition, I can almost assert that, two conditions: "transition matrix $P$ is regular" and "the initial condition has no impact on the eventual behavior (which means convergence)" are equivalent, but I am not going to prove it. Not even a challenge for me.

In [1]:
import numpy as np

In [2]:
transition = np.array([[0.3, 0.7], [0.6, 0.4]])
initial_conditions = [np.array([[0, 1]]), np.array([[0.2, 0.8]]), np.array([[0.4, 0.6]]), np.array([[0.5, 0.5]]), 
                      np.array([[0.6, 0.4]]), np.array([[0.8, 0.2]]), np.array([[0, 1]])]

for condition in initial_conditions:
    m = 0
    while m < 100000:
        condition = np.dot(condition, transition)
        if m >= 99995:
            print(condition)
        m += 1
    print("\n Next_________________________________________________________________________________________Next \n")

[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]

 Next_________________________________________________________________________________________Next 

[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]

 Next_________________________________________________________________________________________Next 

[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]

 Next_________________________________________________________________________________________Next 

[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]

 Next_________________________________________________________________________________________Next 

[[0.46153846 0.53846154]]
[[0.46153846 0.53846154]]
[[0.46153846 0.53846